// <auto-generated />
using System;
using CabinCrew.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CabinCrew.Infrastructure.Migrations
{
    [DbContext(typeof(CabinCrewDbContext))]
    partial class CabinCrewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CabinCrew.Domain.Entities.CabinAttendant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttendantType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_recipes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Recipes");

                    b.Property<string>("_vehicleRestrictions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VehicleRestrictions");

                    b.HasKey("Id");

                    b.ToTable("CabinAttendants", (string)null);
                });

            modelBuilder.Entity("CabinCrew.Domain.Entities.CabinAttendant", b =>
                {
                    b.OwnsOne("CabinCrew.Domain.ValueObjects.AttendantInfo", "Info", b1 =>
                        {
                            b1.Property<Guid>("CabinAttendantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Age")
                                .HasColumnType("int")
                                .HasColumnName("Age");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Gender");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nationality");

                            b1.Property<string>("_knownLanguages")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("KnownLanguages");

                            b1.HasKey("CabinAttendantId");

                            b1.ToTable("CabinAttendants");

                            b1.WithOwner()
                                .HasForeignKey("CabinAttendantId");
                        });

                    b.Navigation("Info")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
